/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as StatusRouteImport } from './routes/status'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as XadmxRouteImport } from './routes/xadmx'
import { Route as AuthenticatedAccountSettingsRouteImport } from './routes/_authenticated/account-settings'
import { Route as AuthenticatedBalanceRouteImport } from './routes/_authenticated/balance'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedBuilderRouteImport } from './routes/_authenticated/builder'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace.index'
import { Route as MarketplaceListingIdRouteImport } from './routes/marketplace.$listingId'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as AuthenticatedAdminAnnouncementsRouteImport } from './routes/_authenticated/admin.announcements'
import { Route as AuthenticatedAdminBlogRouteImport } from './routes/_authenticated/admin.blog'
import { Route as AuthenticatedAdminCodesRouteImport } from './routes/_authenticated/admin.codes'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminStatsRouteImport } from './routes/_authenticated/admin.stats'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedBotsIndexRouteImport } from './routes/_authenticated/bots.index'
import { Route as AuthenticatedBotsNewRouteImport } from './routes/_authenticated/bots.new'
import { Route as AuthenticatedBuilderFlowIdRouteImport } from './routes/_authenticated/builder.$flowId'
import { Route as AuthenticatedMarketplacePublishRouteImport } from './routes/_authenticated/marketplace.publish'
import { Route as ApiPublicDiagRouteImport } from './routes/api.public.diag'
import { Route as AuthDiscordCallbackRouteImport } from './routes/auth.discord.callback'
import { Route as AuthenticatedBotsBotIdIndexRouteImport } from './routes/_authenticated/bots.$botId.index'
import { Route as AuthenticatedBotsBotIdAutomationsRouteImport } from './routes/_authenticated/bots.$botId.automations'
import { Route as AuthenticatedBotsBotIdCommandsRouteImport } from './routes/_authenticated/bots.$botId.commands'
import { Route as AuthenticatedBotsBotIdComponentsRouteImport } from './routes/_authenticated/bots.$botId.components'
import { Route as AuthenticatedBotsBotIdEventsRouteImport } from './routes/_authenticated/bots.$botId.events'
import { Route as AuthenticatedBotsBotIdLogsRouteImport } from './routes/_authenticated/bots.$botId.logs'
import { Route as AuthenticatedBotsBotIdPresenceRouteImport } from './routes/_authenticated/bots.$botId.presence'
import { Route as AuthenticatedBotsBotIdSettingsRouteImport } from './routes/_authenticated/bots.$botId.settings'
import { Route as ApiInternalRuntimeEventsRouteImport } from './routes/api.internal.runtime.events'
import { Route as ApiInternalBotsBotIdTokenRouteImport } from './routes/api.internal.bots.$botId.token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const XadmxRoute = XadmxRouteImport.update({
  id: '/xadmx',
  path: '/xadmx',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountSettingsRoute =
  AuthenticatedAccountSettingsRouteImport.update({
    id: '/account-settings',
    path: '/account-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBalanceRoute = AuthenticatedBalanceRouteImport.update({
  id: '/balance',
  path: '/balance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBuilderRoute = AuthenticatedBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceListingIdRoute = MarketplaceListingIdRouteImport.update({
  id: '/marketplace/$listingId',
  path: '/marketplace/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminAnnouncementsRoute =
  AuthenticatedAdminAnnouncementsRouteImport.update({
    id: '/admin/announcements',
    path: '/admin/announcements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBlogRoute = AuthenticatedAdminBlogRouteImport.update({
  id: '/admin/blog',
  path: '/admin/blog',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminCodesRoute = AuthenticatedAdminCodesRouteImport.update({
  id: '/admin/codes',
  path: '/admin/codes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/admin/reports',
    path: '/admin/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminStatsRoute = AuthenticatedAdminStatsRouteImport.update({
  id: '/admin/stats',
  path: '/admin/stats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBotsIndexRoute = AuthenticatedBotsIndexRouteImport.update({
  id: '/bots/',
  path: '/bots/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBotsNewRoute = AuthenticatedBotsNewRouteImport.update({
  id: '/bots/new',
  path: '/bots/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBuilderFlowIdRoute =
  AuthenticatedBuilderFlowIdRouteImport.update({
    id: '/$flowId',
    path: '/$flowId',
    getParentRoute: () => AuthenticatedBuilderRoute,
  } as any)
const AuthenticatedMarketplacePublishRoute =
  AuthenticatedMarketplacePublishRouteImport.update({
    id: '/marketplace/publish',
    path: '/marketplace/publish',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicDiagRoute = ApiPublicDiagRouteImport.update({
  id: '/api/public/diag',
  path: '/api/public/diag',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDiscordCallbackRoute = AuthDiscordCallbackRouteImport.update({
  id: '/auth/discord/callback',
  path: '/auth/discord/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBotsBotIdIndexRoute =
  AuthenticatedBotsBotIdIndexRouteImport.update({
    id: '/bots/$botId/',
    path: '/bots/$botId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBotsBotIdAutomationsRoute =
  AuthenticatedBotsBotIdAutomationsRouteImport.update({
    id: '/bots/$botId/automations',
    path: '/bots/$botId/automations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBotsBotIdCommandsRoute =
  AuthenticatedBotsBotIdCommandsRouteImport.update({
    id: '/bots/$botId/commands',
    path: '/bots/$botId/commands',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBotsBotIdComponentsRoute =
  AuthenticatedBotsBotIdComponentsRouteImport.update({
    id: '/bots/$botId/components',
    path: '/bots/$botId/components',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBotsBotIdEventsRoute =
  AuthenticatedBotsBotIdEventsRouteImport.update({
    id: '/bots/$botId/events',
    path: '/bots/$botId/events',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBotsBotIdLogsRoute =
  AuthenticatedBotsBotIdLogsRouteImport.update({
    id: '/bots/$botId/logs',
    path: '/bots/$botId/logs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBotsBotIdPresenceRoute =
  AuthenticatedBotsBotIdPresenceRouteImport.update({
    id: '/bots/$botId/presence',
    path: '/bots/$botId/presence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBotsBotIdSettingsRoute =
  AuthenticatedBotsBotIdSettingsRouteImport.update({
    id: '/bots/$botId/settings',
    path: '/bots/$botId/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiInternalRuntimeEventsRoute =
  ApiInternalRuntimeEventsRouteImport.update({
    id: '/api/internal/runtime/events',
    path: '/api/internal/runtime/events',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalBotsBotIdTokenRoute =
  ApiInternalBotsBotIdTokenRouteImport.update({
    id: '/api/internal/bots/$botId/token',
    path: '/api/internal/bots/$botId/token',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/docs': typeof DocsRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/xadmx': typeof XadmxRoute
  '/account-settings': typeof AuthenticatedAccountSettingsRoute
  '/balance': typeof AuthenticatedBalanceRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/builder': typeof AuthenticatedBuilderRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/marketplace/$listingId': typeof MarketplaceListingIdRoute
  '/u/$username': typeof UUsernameRoute
  '/blog/': typeof BlogIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/codes': typeof AuthenticatedAdminCodesRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/stats': typeof AuthenticatedAdminStatsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/bots/new': typeof AuthenticatedBotsNewRoute
  '/builder/$flowId': typeof AuthenticatedBuilderFlowIdRoute
  '/marketplace/publish': typeof AuthenticatedMarketplacePublishRoute
  '/api/public/diag': typeof ApiPublicDiagRoute
  '/auth/discord/callback': typeof AuthDiscordCallbackRoute
  '/bots/': typeof AuthenticatedBotsIndexRoute
  '/bots/$botId/automations': typeof AuthenticatedBotsBotIdAutomationsRoute
  '/bots/$botId/commands': typeof AuthenticatedBotsBotIdCommandsRoute
  '/bots/$botId/components': typeof AuthenticatedBotsBotIdComponentsRoute
  '/bots/$botId/events': typeof AuthenticatedBotsBotIdEventsRoute
  '/bots/$botId/logs': typeof AuthenticatedBotsBotIdLogsRoute
  '/bots/$botId/presence': typeof AuthenticatedBotsBotIdPresenceRoute
  '/bots/$botId/settings': typeof AuthenticatedBotsBotIdSettingsRoute
  '/api/internal/runtime/events': typeof ApiInternalRuntimeEventsRoute
  '/bots/$botId/': typeof AuthenticatedBotsBotIdIndexRoute
  '/api/internal/bots/$botId/token': typeof ApiInternalBotsBotIdTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/docs': typeof DocsRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/xadmx': typeof XadmxRoute
  '/account-settings': typeof AuthenticatedAccountSettingsRoute
  '/balance': typeof AuthenticatedBalanceRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/builder': typeof AuthenticatedBuilderRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/marketplace/$listingId': typeof MarketplaceListingIdRoute
  '/u/$username': typeof UUsernameRoute
  '/blog': typeof BlogIndexRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/codes': typeof AuthenticatedAdminCodesRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/stats': typeof AuthenticatedAdminStatsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/bots/new': typeof AuthenticatedBotsNewRoute
  '/builder/$flowId': typeof AuthenticatedBuilderFlowIdRoute
  '/marketplace/publish': typeof AuthenticatedMarketplacePublishRoute
  '/api/public/diag': typeof ApiPublicDiagRoute
  '/auth/discord/callback': typeof AuthDiscordCallbackRoute
  '/bots': typeof AuthenticatedBotsIndexRoute
  '/bots/$botId/automations': typeof AuthenticatedBotsBotIdAutomationsRoute
  '/bots/$botId/commands': typeof AuthenticatedBotsBotIdCommandsRoute
  '/bots/$botId/components': typeof AuthenticatedBotsBotIdComponentsRoute
  '/bots/$botId/events': typeof AuthenticatedBotsBotIdEventsRoute
  '/bots/$botId/logs': typeof AuthenticatedBotsBotIdLogsRoute
  '/bots/$botId/presence': typeof AuthenticatedBotsBotIdPresenceRoute
  '/bots/$botId/settings': typeof AuthenticatedBotsBotIdSettingsRoute
  '/api/internal/runtime/events': typeof ApiInternalRuntimeEventsRoute
  '/bots/$botId': typeof AuthenticatedBotsBotIdIndexRoute
  '/api/internal/bots/$botId/token': typeof ApiInternalBotsBotIdTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/docs': typeof DocsRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/xadmx': typeof XadmxRoute
  '/_authenticated/account-settings': typeof AuthenticatedAccountSettingsRoute
  '/_authenticated/balance': typeof AuthenticatedBalanceRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/builder': typeof AuthenticatedBuilderRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/marketplace/$listingId': typeof MarketplaceListingIdRoute
  '/u/$username': typeof UUsernameRoute
  '/blog/': typeof BlogIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/_authenticated/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/_authenticated/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/_authenticated/admin/codes': typeof AuthenticatedAdminCodesRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/stats': typeof AuthenticatedAdminStatsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/bots/new': typeof AuthenticatedBotsNewRoute
  '/_authenticated/builder/$flowId': typeof AuthenticatedBuilderFlowIdRoute
  '/_authenticated/marketplace/publish': typeof AuthenticatedMarketplacePublishRoute
  '/api/public/diag': typeof ApiPublicDiagRoute
  '/auth/discord/callback': typeof AuthDiscordCallbackRoute
  '/_authenticated/bots/': typeof AuthenticatedBotsIndexRoute
  '/_authenticated/bots/$botId/automations': typeof AuthenticatedBotsBotIdAutomationsRoute
  '/_authenticated/bots/$botId/commands': typeof AuthenticatedBotsBotIdCommandsRoute
  '/_authenticated/bots/$botId/components': typeof AuthenticatedBotsBotIdComponentsRoute
  '/_authenticated/bots/$botId/events': typeof AuthenticatedBotsBotIdEventsRoute
  '/_authenticated/bots/$botId/logs': typeof AuthenticatedBotsBotIdLogsRoute
  '/_authenticated/bots/$botId/presence': typeof AuthenticatedBotsBotIdPresenceRoute
  '/_authenticated/bots/$botId/settings': typeof AuthenticatedBotsBotIdSettingsRoute
  '/api/internal/runtime/events': typeof ApiInternalRuntimeEventsRoute
  '/_authenticated/bots/$botId/': typeof AuthenticatedBotsBotIdIndexRoute
  '/api/internal/bots/$botId/token': typeof ApiInternalBotsBotIdTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/changelog'
    | '/docs'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/register'
    | '/status'
    | '/terms'
    | '/xadmx'
    | '/account-settings'
    | '/balance'
    | '/billing'
    | '/builder'
    | '/dashboard'
    | '/blog/$slug'
    | '/marketplace/$listingId'
    | '/u/$username'
    | '/blog/'
    | '/marketplace/'
    | '/admin/announcements'
    | '/admin/blog'
    | '/admin/codes'
    | '/admin/reports'
    | '/admin/stats'
    | '/admin/users'
    | '/bots/new'
    | '/builder/$flowId'
    | '/marketplace/publish'
    | '/api/public/diag'
    | '/auth/discord/callback'
    | '/bots/'
    | '/bots/$botId/automations'
    | '/bots/$botId/commands'
    | '/bots/$botId/components'
    | '/bots/$botId/events'
    | '/bots/$botId/logs'
    | '/bots/$botId/presence'
    | '/bots/$botId/settings'
    | '/api/internal/runtime/events'
    | '/bots/$botId/'
    | '/api/internal/bots/$botId/token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changelog'
    | '/docs'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/register'
    | '/status'
    | '/terms'
    | '/xadmx'
    | '/account-settings'
    | '/balance'
    | '/billing'
    | '/builder'
    | '/dashboard'
    | '/blog/$slug'
    | '/marketplace/$listingId'
    | '/u/$username'
    | '/blog'
    | '/marketplace'
    | '/admin/announcements'
    | '/admin/blog'
    | '/admin/codes'
    | '/admin/reports'
    | '/admin/stats'
    | '/admin/users'
    | '/bots/new'
    | '/builder/$flowId'
    | '/marketplace/publish'
    | '/api/public/diag'
    | '/auth/discord/callback'
    | '/bots'
    | '/bots/$botId/automations'
    | '/bots/$botId/commands'
    | '/bots/$botId/components'
    | '/bots/$botId/events'
    | '/bots/$botId/logs'
    | '/bots/$botId/presence'
    | '/bots/$botId/settings'
    | '/api/internal/runtime/events'
    | '/bots/$botId'
    | '/api/internal/bots/$botId/token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/changelog'
    | '/docs'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/register'
    | '/status'
    | '/terms'
    | '/xadmx'
    | '/_authenticated/account-settings'
    | '/_authenticated/balance'
    | '/_authenticated/billing'
    | '/_authenticated/builder'
    | '/_authenticated/dashboard'
    | '/blog/$slug'
    | '/marketplace/$listingId'
    | '/u/$username'
    | '/blog/'
    | '/marketplace/'
    | '/_authenticated/admin/announcements'
    | '/_authenticated/admin/blog'
    | '/_authenticated/admin/codes'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/stats'
    | '/_authenticated/admin/users'
    | '/_authenticated/bots/new'
    | '/_authenticated/builder/$flowId'
    | '/_authenticated/marketplace/publish'
    | '/api/public/diag'
    | '/auth/discord/callback'
    | '/_authenticated/bots/'
    | '/_authenticated/bots/$botId/automations'
    | '/_authenticated/bots/$botId/commands'
    | '/_authenticated/bots/$botId/components'
    | '/_authenticated/bots/$botId/events'
    | '/_authenticated/bots/$botId/logs'
    | '/_authenticated/bots/$botId/presence'
    | '/_authenticated/bots/$botId/settings'
    | '/api/internal/runtime/events'
    | '/_authenticated/bots/$botId/'
    | '/api/internal/bots/$botId/token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ChangelogRoute: typeof ChangelogRoute
  DocsRoute: typeof DocsRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  StatusRoute: typeof StatusRoute
  TermsRoute: typeof TermsRoute
  XadmxRoute: typeof XadmxRoute
  BlogSlugRoute: typeof BlogSlugRoute
  MarketplaceListingIdRoute: typeof MarketplaceListingIdRoute
  UUsernameRoute: typeof UUsernameRoute
  BlogIndexRoute: typeof BlogIndexRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
  ApiPublicDiagRoute: typeof ApiPublicDiagRoute
  AuthDiscordCallbackRoute: typeof AuthDiscordCallbackRoute
  ApiInternalRuntimeEventsRoute: typeof ApiInternalRuntimeEventsRoute
  ApiInternalBotsBotIdTokenRoute: typeof ApiInternalBotsBotIdTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xadmx': {
      id: '/xadmx'
      path: '/xadmx'
      fullPath: '/xadmx'
      preLoaderRoute: typeof XadmxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account-settings': {
      id: '/_authenticated/account-settings'
      path: '/account-settings'
      fullPath: '/account-settings'
      preLoaderRoute: typeof AuthenticatedAccountSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/balance': {
      id: '/_authenticated/balance'
      path: '/balance'
      fullPath: '/balance'
      preLoaderRoute: typeof AuthenticatedBalanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/builder': {
      id: '/_authenticated/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof AuthenticatedBuilderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/$listingId': {
      id: '/marketplace/$listingId'
      path: '/marketplace/$listingId'
      fullPath: '/marketplace/$listingId'
      preLoaderRoute: typeof MarketplaceListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/announcements': {
      id: '/_authenticated/admin/announcements'
      path: '/admin/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AuthenticatedAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/blog': {
      id: '/_authenticated/admin/blog'
      path: '/admin/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AuthenticatedAdminBlogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/codes': {
      id: '/_authenticated/admin/codes'
      path: '/admin/codes'
      fullPath: '/admin/codes'
      preLoaderRoute: typeof AuthenticatedAdminCodesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/stats': {
      id: '/_authenticated/admin/stats'
      path: '/admin/stats'
      fullPath: '/admin/stats'
      preLoaderRoute: typeof AuthenticatedAdminStatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bots/': {
      id: '/_authenticated/bots/'
      path: '/bots'
      fullPath: '/bots/'
      preLoaderRoute: typeof AuthenticatedBotsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bots/new': {
      id: '/_authenticated/bots/new'
      path: '/bots/new'
      fullPath: '/bots/new'
      preLoaderRoute: typeof AuthenticatedBotsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/builder/$flowId': {
      id: '/_authenticated/builder/$flowId'
      path: '/$flowId'
      fullPath: '/builder/$flowId'
      preLoaderRoute: typeof AuthenticatedBuilderFlowIdRouteImport
      parentRoute: typeof AuthenticatedBuilderRoute
    }
    '/_authenticated/marketplace/publish': {
      id: '/_authenticated/marketplace/publish'
      path: '/marketplace/publish'
      fullPath: '/marketplace/publish'
      preLoaderRoute: typeof AuthenticatedMarketplacePublishRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/diag': {
      id: '/api/public/diag'
      path: '/api/public/diag'
      fullPath: '/api/public/diag'
      preLoaderRoute: typeof ApiPublicDiagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/discord/callback': {
      id: '/auth/discord/callback'
      path: '/auth/discord/callback'
      fullPath: '/auth/discord/callback'
      preLoaderRoute: typeof AuthDiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/bots/$botId/': {
      id: '/_authenticated/bots/$botId/'
      path: '/bots/$botId'
      fullPath: '/bots/$botId/'
      preLoaderRoute: typeof AuthenticatedBotsBotIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bots/$botId/automations': {
      id: '/_authenticated/bots/$botId/automations'
      path: '/bots/$botId/automations'
      fullPath: '/bots/$botId/automations'
      preLoaderRoute: typeof AuthenticatedBotsBotIdAutomationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bots/$botId/commands': {
      id: '/_authenticated/bots/$botId/commands'
      path: '/bots/$botId/commands'
      fullPath: '/bots/$botId/commands'
      preLoaderRoute: typeof AuthenticatedBotsBotIdCommandsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bots/$botId/components': {
      id: '/_authenticated/bots/$botId/components'
      path: '/bots/$botId/components'
      fullPath: '/bots/$botId/components'
      preLoaderRoute: typeof AuthenticatedBotsBotIdComponentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bots/$botId/events': {
      id: '/_authenticated/bots/$botId/events'
      path: '/bots/$botId/events'
      fullPath: '/bots/$botId/events'
      preLoaderRoute: typeof AuthenticatedBotsBotIdEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bots/$botId/logs': {
      id: '/_authenticated/bots/$botId/logs'
      path: '/bots/$botId/logs'
      fullPath: '/bots/$botId/logs'
      preLoaderRoute: typeof AuthenticatedBotsBotIdLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bots/$botId/presence': {
      id: '/_authenticated/bots/$botId/presence'
      path: '/bots/$botId/presence'
      fullPath: '/bots/$botId/presence'
      preLoaderRoute: typeof AuthenticatedBotsBotIdPresenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bots/$botId/settings': {
      id: '/_authenticated/bots/$botId/settings'
      path: '/bots/$botId/settings'
      fullPath: '/bots/$botId/settings'
      preLoaderRoute: typeof AuthenticatedBotsBotIdSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/internal/runtime/events': {
      id: '/api/internal/runtime/events'
      path: '/api/internal/runtime/events'
      fullPath: '/api/internal/runtime/events'
      preLoaderRoute: typeof ApiInternalRuntimeEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/bots/$botId/token': {
      id: '/api/internal/bots/$botId/token'
      path: '/api/internal/bots/$botId/token'
      fullPath: '/api/internal/bots/$botId/token'
      preLoaderRoute: typeof ApiInternalBotsBotIdTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedBuilderRouteChildren {
  AuthenticatedBuilderFlowIdRoute: typeof AuthenticatedBuilderFlowIdRoute
}

const AuthenticatedBuilderRouteChildren: AuthenticatedBuilderRouteChildren = {
  AuthenticatedBuilderFlowIdRoute: AuthenticatedBuilderFlowIdRoute,
}

const AuthenticatedBuilderRouteWithChildren =
  AuthenticatedBuilderRoute._addFileChildren(AuthenticatedBuilderRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountSettingsRoute: typeof AuthenticatedAccountSettingsRoute
  AuthenticatedBalanceRoute: typeof AuthenticatedBalanceRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedBuilderRoute: typeof AuthenticatedBuilderRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAdminAnnouncementsRoute: typeof AuthenticatedAdminAnnouncementsRoute
  AuthenticatedAdminBlogRoute: typeof AuthenticatedAdminBlogRoute
  AuthenticatedAdminCodesRoute: typeof AuthenticatedAdminCodesRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminStatsRoute: typeof AuthenticatedAdminStatsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedBotsNewRoute: typeof AuthenticatedBotsNewRoute
  AuthenticatedMarketplacePublishRoute: typeof AuthenticatedMarketplacePublishRoute
  AuthenticatedBotsIndexRoute: typeof AuthenticatedBotsIndexRoute
  AuthenticatedBotsBotIdAutomationsRoute: typeof AuthenticatedBotsBotIdAutomationsRoute
  AuthenticatedBotsBotIdCommandsRoute: typeof AuthenticatedBotsBotIdCommandsRoute
  AuthenticatedBotsBotIdComponentsRoute: typeof AuthenticatedBotsBotIdComponentsRoute
  AuthenticatedBotsBotIdEventsRoute: typeof AuthenticatedBotsBotIdEventsRoute
  AuthenticatedBotsBotIdLogsRoute: typeof AuthenticatedBotsBotIdLogsRoute
  AuthenticatedBotsBotIdPresenceRoute: typeof AuthenticatedBotsBotIdPresenceRoute
  AuthenticatedBotsBotIdSettingsRoute: typeof AuthenticatedBotsBotIdSettingsRoute
  AuthenticatedBotsBotIdIndexRoute: typeof AuthenticatedBotsBotIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountSettingsRoute: AuthenticatedAccountSettingsRoute,
  AuthenticatedBalanceRoute: AuthenticatedBalanceRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedBuilderRoute: AuthenticatedBuilderRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAdminAnnouncementsRoute: AuthenticatedAdminAnnouncementsRoute,
  AuthenticatedAdminBlogRoute: AuthenticatedAdminBlogRoute,
  AuthenticatedAdminCodesRoute: AuthenticatedAdminCodesRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminStatsRoute: AuthenticatedAdminStatsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedBotsNewRoute: AuthenticatedBotsNewRoute,
  AuthenticatedMarketplacePublishRoute: AuthenticatedMarketplacePublishRoute,
  AuthenticatedBotsIndexRoute: AuthenticatedBotsIndexRoute,
  AuthenticatedBotsBotIdAutomationsRoute:
    AuthenticatedBotsBotIdAutomationsRoute,
  AuthenticatedBotsBotIdCommandsRoute: AuthenticatedBotsBotIdCommandsRoute,
  AuthenticatedBotsBotIdComponentsRoute: AuthenticatedBotsBotIdComponentsRoute,
  AuthenticatedBotsBotIdEventsRoute: AuthenticatedBotsBotIdEventsRoute,
  AuthenticatedBotsBotIdLogsRoute: AuthenticatedBotsBotIdLogsRoute,
  AuthenticatedBotsBotIdPresenceRoute: AuthenticatedBotsBotIdPresenceRoute,
  AuthenticatedBotsBotIdSettingsRoute: AuthenticatedBotsBotIdSettingsRoute,
  AuthenticatedBotsBotIdIndexRoute: AuthenticatedBotsBotIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ChangelogRoute: ChangelogRoute,
  DocsRoute: DocsRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  StatusRoute: StatusRoute,
  TermsRoute: TermsRoute,
  XadmxRoute: XadmxRoute,
  BlogSlugRoute: BlogSlugRoute,
  MarketplaceListingIdRoute: MarketplaceListingIdRoute,
  UUsernameRoute: UUsernameRoute,
  BlogIndexRoute: BlogIndexRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
  ApiPublicDiagRoute: ApiPublicDiagRoute,
  AuthDiscordCallbackRoute: AuthDiscordCallbackRoute,
  ApiInternalRuntimeEventsRoute: ApiInternalRuntimeEventsRoute,
  ApiInternalBotsBotIdTokenRoute: ApiInternalBotsBotIdTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
