CREATE TABLE public.flow_templates (
  id text PRIMARY KEY,
  name text NOT NULL,
  description text NOT NULL DEFAULT '',
  category text NOT NULL,
  icon text NOT NULL DEFAULT 'Sparkles',
  nodes jsonb NOT NULL DEFAULT '[]'::jsonb,
  edges jsonb NOT NULL DEFAULT '[]'::jsonb,
  is_public boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

GRANT SELECT ON public.flow_templates TO anon;
GRANT SELECT ON public.flow_templates TO authenticated;
GRANT ALL ON public.flow_templates TO service_role;

ALTER TABLE public.flow_templates ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public templates are readable by everyone"
ON public.flow_templates FOR SELECT
USING (is_public = true);

CREATE TRIGGER flow_templates_touch_updated_at
BEFORE UPDATE ON public.flow_templates
FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

INSERT INTO public.flow_templates (id, name, description, category, icon, nodes, edges, is_public) VALUES
  ('ban-command', 'Ban Command', 'Prebuilt moderation workflow triggered by /ban.', 'Moderation', 'Sparkles', '[{"key":"cmd","type":"slash-command","x":0,"y":0,"title":"/ban","config":{"name":"ban","description":"Ban a member from the server."},"options":[{"id":"opt_mt8lgoee_1n0if","name":"user","description":"Member to ban","type":"user","required":true,"autocomplete":false},{"id":"opt_mt8lgoee_2m765","name":"reason","description":"Reason for the ban","type":"string","required":false,"autocomplete":false}]},{"key":"perm","type":"check-permission","x":0,"y":190,"config":{"permission":"BanMembers","user":"{user}"}},{"key":"ban","type":"ban-user","x":-190,"y":400,"config":{"user":"{user}","reason":"{reason}"}},{"key":"ok","type":"send-embed","x":-190,"y":600,"embed":{"id":"emb_mt8lgoee_3wltu","author":{"name":"","icon":"","url":""},"title":"🔨 User banned","description":"{user} has been banned.\n**Reason:** {reason}","url":"","color":"#ED4245","thumbnail":"","image":"","fields":[],"footer":{"text":"Bottly moderation","icon":""},"timestamp":true},"components":[{"id":"cmp_mt8lgoee_44lzk","type":"button","label":"Appeal","style":"secondary","emoji":"","action":"open_ticket","url":"","disabled":false,"placeholder":"Click me","options":[]}]},{"key":"err","type":"send-embed","x":260,"y":400,"title":"Send Error Embed","config":{"ephemeral":true},"embed":{"id":"emb_mt8lgoee_5fkts","author":{"name":"","icon":"","url":""},"title":"Missing permission","description":"You need the **Ban Members** permission to use this command.","url":"","color":"#F0B232","thumbnail":"","image":"","fields":[],"footer":{"text":"","icon":""},"timestamp":false}}]'::jsonb, '[{"from":"cmd","to":"perm"},{"from":"perm","to":"ban","handle":"true"},{"from":"perm","to":"err","handle":"false"},{"from":"ban","to":"ok"}]'::jsonb, true),
  ('ticket-system', 'Ticket System', 'Prebuilt tickets workflow triggered by /ticket.', 'Tickets', 'Sparkles', '[{"key":"cmd","type":"slash-command","x":0,"y":0,"title":"/ticket","config":{"name":"ticket","description":"Open the ticket panel."}},{"key":"panel","type":"send-embed","x":0,"y":190,"embed":{"id":"emb_mt8lgoee_60ga1","author":{"name":"","icon":"","url":""},"title":"🎫 Create a ticket","description":"Need help? Click the button below and our team will be with you shortly.","url":"","color":"#5865F2","thumbnail":"","image":"","fields":[],"footer":{"text":"Support team","icon":""},"timestamp":true},"components":[{"id":"cmp_mt8lgoee_7fhp9","type":"button","label":"🎫 Create Ticket","style":"primary","emoji":"","action":"open_ticket","url":"","disabled":false,"placeholder":"Click me","options":[]}]},{"key":"click","type":"button-click","x":0,"y":400,"config":{"customId":"create_ticket"}},{"key":"channel","type":"send-message","x":0,"y":590,"title":"Create Ticket Channel","config":{"channel":"ticket-{username}","content":"Ticket channel created."}},{"key":"welcome","type":"send-embed","x":0,"y":790,"title":"Send Welcome Embed","embed":{"id":"emb_mt8lgoee_83hn0","author":{"name":"","icon":"","url":""},"title":"Ticket opened","description":"Hey {user}, describe your issue and a moderator will reply soon.","url":"","color":"#23A55A","thumbnail":"","image":"","fields":[],"footer":{"text":"","icon":""},"timestamp":true},"components":[{"id":"cmp_mt8lgoee_9bfix","type":"button","label":"Close ticket","style":"danger","emoji":"","action":"open_ticket","url":"","disabled":false,"placeholder":"Click me","options":[]}]}]'::jsonb, '[{"from":"cmd","to":"panel"},{"from":"panel","to":"click"},{"from":"click","to":"channel"},{"from":"channel","to":"welcome"}]'::jsonb, true),
  ('verification', 'Verification System', 'Prebuilt verification workflow triggered by /verify.', 'Verification', 'Sparkles', '[{"key":"cmd","type":"slash-command","x":0,"y":0,"title":"/verify","config":{"name":"verify","description":"Post the verification panel."}},{"key":"panel","type":"send-embed","x":0,"y":190,"embed":{"id":"emb_mt8lgoee_az6aj","author":{"name":"","icon":"","url":""},"title":"✅ Verify yourself","description":"Click **Verify** to gain access to {server.name}.","url":"","color":"#23A55A","thumbnail":"","image":"","fields":[],"footer":{"text":"","icon":""},"timestamp":true},"components":[{"id":"cmp_mt8lgoee_b1vwr","type":"button","label":"Verify","style":"success","emoji":"","action":"open_ticket","url":"","disabled":false,"placeholder":"Click me","options":[]}]},{"key":"click","type":"button-click","x":0,"y":400,"config":{"customId":"verify"}},{"key":"role","type":"add-role","x":0,"y":580,"config":{"user":"{user}","role":"@Verified"}},{"key":"done","type":"send-embed","x":0,"y":760,"title":"Send Success Message","config":{"ephemeral":true},"embed":{"id":"emb_mt8lgoee_c6hp2","author":{"name":"","icon":"","url":""},"title":"You''re verified!","description":"Welcome to {server.name}, {username}.","url":"","color":"#5865F2","thumbnail":"","image":"","fields":[],"footer":{"text":"","icon":""},"timestamp":false}}]'::jsonb, '[{"from":"cmd","to":"panel"},{"from":"panel","to":"click"},{"from":"click","to":"role"},{"from":"role","to":"done"}]'::jsonb, true),
  ('welcome-flow', 'Welcome Greeter', 'Prebuilt welcome workflow triggered by Member Joined.', 'Welcome', 'Sparkles', '[{"key":"join","type":"member-joined","x":0,"y":0},{"key":"embed","type":"send-embed","x":0,"y":190,"config":{"channel":"#welcome"},"embed":{"id":"emb_mt8lgoee_dxan9","author":{"name":"","icon":"","url":""},"title":"👋 Welcome {username}!","description":"You are member #{server.memberCount} of {server.name}. Enjoy your stay!","url":"","color":"#7C5CFC","thumbnail":"","image":"","fields":[],"footer":{"text":"","icon":""},"timestamp":true}},{"key":"role","type":"add-role","x":0,"y":400,"config":{"user":"{user}","role":"@Member"}}]'::jsonb, '[{"from":"join","to":"embed"},{"from":"embed","to":"role"}]'::jsonb, true),
  ('poll-utility', 'Quick Poll', 'Prebuilt utility workflow triggered by /poll.', 'Utility', 'Sparkles', '[{"key":"cmd","type":"slash-command","x":0,"y":0,"title":"/poll","config":{"name":"poll","description":"Start a quick poll."},"options":[{"id":"opt_mt8lgoee_elf1z","name":"question","description":"Poll question","type":"string","required":true,"autocomplete":false}]},{"key":"embed","type":"send-embed","x":0,"y":190,"embed":{"id":"emb_mt8lgoee_f68hu","author":{"name":"","icon":"","url":""},"title":"📊 Poll","description":"{question}","url":"","color":"#F0B232","thumbnail":"","image":"","fields":[],"footer":{"text":"Vote below","icon":""},"timestamp":true},"components":[{"id":"cmp_mt8lgoee_gbekt","type":"button","label":"Yes","style":"success","emoji":"","action":"open_ticket","url":"","disabled":false,"placeholder":"Click me","options":[]},{"id":"cmp_mt8lgoee_hi9gg","type":"button","label":"No","style":"danger","emoji":"","action":"open_ticket","url":"","disabled":false,"placeholder":"Click me","options":[]}]},{"key":"select","type":"dropdown-select","x":0,"y":420,"config":{"customId":"poll_vote"}},{"key":"inc","type":"increment","x":0,"y":600,"config":{"name":"votes","amount":1}}]'::jsonb, '[{"from":"cmd","to":"embed"},{"from":"embed","to":"select"},{"from":"select","to":"inc"}]'::jsonb, true),
  ('mod-logging', 'Message Delete Log', 'Prebuilt logging workflow triggered by Message Received.', 'Logging', 'Sparkles', '[{"key":"msg","type":"message-received","x":0,"y":0},{"key":"check","type":"contains","x":0,"y":190,"config":{"text":"{message.content}","value":"discord.gg/"}},{"key":"delete","type":"delete-messages","x":-190,"y":400,"config":{"amount":1,"channel":"{channel}"}},{"key":"log","type":"send-embed","x":-190,"y":590,"title":"Log Entry","config":{"channel":"#mod-logs"},"embed":{"id":"emb_mt8lgoee_iyofb","author":{"name":"","icon":"","url":""},"title":"🚫 Invite link removed","description":"Message from {user} in {channel} was deleted.","url":"","color":"#ED4245","thumbnail":"","image":"","fields":[],"footer":{"text":"","icon":""},"timestamp":true}}]'::jsonb, '[{"from":"msg","to":"check"},{"from":"check","to":"delete","handle":"true"},{"from":"delete","to":"log"}]'::jsonb, true),
  ('giveaway', 'Giveaway Launcher', 'Prebuilt giveaways workflow triggered by /giveaway.', 'Giveaways', 'Sparkles', '[{"key":"cmd","type":"slash-command","x":0,"y":0,"title":"/giveaway","config":{"name":"giveaway","description":"Start a giveaway."},"options":[{"id":"opt_mt8lgoee_jyc0d","name":"prize","description":"What to give away","type":"string","required":true,"autocomplete":false}]},{"key":"embed","type":"send-embed","x":0,"y":190,"embed":{"id":"emb_mt8lgoee_ky402","author":{"name":"","icon":"","url":""},"title":"🎉 Giveaway!","description":"Prize: **{prize}**\nClick **Enter** to join.","url":"","color":"#7C5CFC","thumbnail":"","image":"","fields":[],"footer":{"text":"Ends soon","icon":""},"timestamp":true},"components":[{"id":"cmp_mt8lgoee_ll7yu","type":"button","label":"🎉 Enter","style":"primary","emoji":"","action":"open_ticket","url":"","disabled":false,"placeholder":"Click me","options":[]}]},{"key":"click","type":"button-click","x":0,"y":420,"config":{"customId":"giveaway_enter"}},{"key":"cooldown","type":"cooldown","x":0,"y":600,"config":{"seconds":60,"scope":"user"}},{"key":"store","type":"set-variable","x":0,"y":790,"config":{"name":"entries","value":"{user.id}"}}]'::jsonb, '[{"from":"cmd","to":"embed"},{"from":"embed","to":"click"},{"from":"click","to":"cooldown"},{"from":"cooldown","to":"store"}]'::jsonb, true);